#include "libftprintf.h" /* Моя библиотека */
#include <limits.h> /* Для INT_MIN */

int		main(void)
{
	/* Тестирование */
//	printf("Hello it's me %s, year %d and my first letter %c %%\n", "OLEG", 38, 'o');
//	ft_printf("Hello it's me %s, year %d and my first letter %c %%\n", "OLEG", 38, 'o');
//	ft_printf("%d\n%s\n%c\n%%\n%s\n%d\n", 21, "lol", 't', "kek", 17);

//	int r00 = 0;
//	char *s_hello = "hello world";
//	char	a01;
//	unsigned char a02;
//	short a03;
//	unsigned short a04;
//	int a05;
//	unsigned int a06;
//	long a07;
//	unsigned long a08;
//	long long a09;
//	unsigned long long a10;
//	char *a11;
//	void *a12;

//	int res_pf;
//	int res_my;
//	res_pf = printf("pf: |%*.2s|\n",-10,"HelloWorld");
//	res_my = ft_printf("my: |%*.2s|\n",-10,"HelloWorld");
//	printf("len pf: %d\n", res_pf);
//	printf("len my: %d\n", res_my);
//	int		a = -4;
//	int		b = 0;
//	char	c = 'a';
//	int		d = 2147483647;
//	int		e = -2147483648;
//	int		f = 42;
//	int		g = 25;
//	int		h = 4200;
//	int		i = 8;
//	int		j = -12;
//	int		k = 123456789;
//	int		l = 0;
//	int		m = -12345678;
//	char	*n = "abcdefghijklmnop";
//	char	*o = "-a";
//	char	*p = "-12";
//	char	*q = "0";
//	char	*r = "%%";
//	char	*s = "-2147483648";
//	char	*t = "0x12345678";
//	char	*u = "-0";
	
	printf("|%1.d|\n", 0);
	ft_printf("|%1.d|\n",0);

	/* МОИ ТЕСТЫ */
//	ft_printf("-------------------------------------\n");
//	ft_printf("---------------d and i---------------\n");
//	ft_printf("-------------------------------------\n");
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%d_neg = |%d|\n", -42);
//	result_my = ft_printf("my: %%d_neg = |%d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-d = |%-d|\n", 42);
//	result_my = ft_printf("my: %%-d = |%-d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0d = |%0d|\n", 42);
//	result_my = ft_printf("my: %%0d = |%0d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-d_neg = |%-d|\n", -42);
//	result_my = ft_printf("my: %%-d_neg = |%-d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0d_neg = |%0d|\n", -42);
//	result_my = ft_printf("my: %%0d_neg = |%0d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3d = |%3d|\n", 42);
//	result_my = ft_printf("my: %%3d = |%3d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3d = |%-3d|\n", 42);
//	result_my = ft_printf("my: %%-3d = |%-3d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03d = |%03d|\n", 42);
//	result_my = ft_printf("my: %%03d = |%03d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3d_neg = |%3d|\n", -42);
//	result_my = ft_printf("my: %%3d_neg = |%3d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3d_neg = |%-3d|\n", -42);
//	result_my = ft_printf("my: %%-3d_neg = |%-3d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03d_neg = |%03d|\n", -42);
//	result_my = ft_printf("my: %%03d_neg = |%03d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13d = |%13d|\n", 424242);
//	result_my = ft_printf("my: %%13d = |%13d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13d_neg = |%13d|\n", -424242);
//	result_my = ft_printf("my: %%13d_neg = |%13d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6d = |%6d|\n", 424242);
//	result_my = ft_printf("my: %%6d = |%6d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6d_neg = |%6d|\n", -424242);
//	result_my = ft_printf("my: %%6d_neg = |%6d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13d = |%-13d|\n", 424242);
//	result_my = ft_printf("my: %%-13d = |%-13d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13d_neg = |%-13d|\n", -424242);
//	result_my = ft_printf("my: %%-13d_neg = |%-13d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013d = |%013d|\n", 424242);
//	result_my = ft_printf("my: %%013d = |%013d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013d_neg = |%013d|\n", -424242);
//	result_my = ft_printf("my: %%013d_neg = |%013d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	result_pf = printf("pf: %%.d = |%.d|\n", 42);
//	result_my = ft_printf("my: %%.d = |%.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%.d_neg = |%.d|\n", -42);
//	result_my = ft_printf("my: %%.d_neg = |%.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-.d = |%-.d|\n", 42);
//	result_my = ft_printf("my: %%-.d = |%-.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0.d = |%0.d|\n", 42);
//	result_my = ft_printf("my: %%0.d = |%0.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-.d_neg = |%-.d|\n", -42);
//	result_my = ft_printf("my: %%-.d_neg = |%-.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0.d_neg = |%0.d|\n", -42);
//	result_my = ft_printf("my: %%0.d_neg = |%0.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3.d = |%3.d|\n", 42);
//	result_my = ft_printf("my: %%3.d = |%3.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3.d = |%-3.d|\n", 42);
//	result_my = ft_printf("my: %%-3.d = |%-3.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03.d = |%03.d|\n", 42);
//	result_my = ft_printf("my: %%03.d = |%03.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3.d_neg = |%3.d|\n", -42);
//	result_my = ft_printf("my: %%3.d_neg = |%3.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3.d_neg = |%-3.d|\n", -42);
//	result_my = ft_printf("my: %%-3.d_neg = |%-3.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03.d_neg = |%03.d|\n", -42);
//	result_my = ft_printf("my: %%03.d_neg = |%03.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13.d = |%13.d|\n", 424242);
//	result_my = ft_printf("my: %%13.d = |%13.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13.d_neg = |%13.d|\n", -424242);
//	result_my = ft_printf("my: %%13.d_neg = |%13.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6.d = |%6.d|\n", 424242);
//	result_my = ft_printf("my: %%6.d = |%6.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6.d_neg = |%6.d|\n", -424242);
//	result_my = ft_printf("my: %%6.d_neg = |%6.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13.d = |%-13.d|\n", 424242);
//	result_my = ft_printf("my: %%-13.d = |%-13.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13.d_neg = |%-13.d|\n", -424242);
//	result_my = ft_printf("my: %%-13.d_neg = |%-13.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013.d = |%013.d|\n", 424242);
//	result_my = ft_printf("my: %%013.d = |%013.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013.d_neg = |%013.d|\n", -424242);
//	result_my = ft_printf("my: %%013.d_neg = |%013.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
	
	
//	ft_printf("-------------------------------------\n");
//	ft_printf("------------------p------------------\n");
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%p = |%p|\n", &a01);
//	result_my = ft_printf("my: %%p = |%p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-p = |%-p|\n", &a01);
//	result_my = ft_printf("my: %%-p = |%-p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%1p = |%1p|\n", &a01);
//	result_my = ft_printf("my: %%1p = |%1p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%4p = |%4p|\n", &a01);
//	result_my = ft_printf("my: %%4p = |%4p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-4p = |%-4p|\n", &a01);
//	result_my = ft_printf("my: %%-4p = |%-4p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%20p = |%20p|\n", &a01);
//	result_my = ft_printf("my: %%20p = |%20p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-20p = |%-20p|\n", &a01);
//	result_my = ft_printf("my: %%-20p = |%-20p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-20p = |%-20p|\n", &a01);
//	result_my = ft_printf("my: %%-20p = |%-20p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%*p = |%*p|\n", 21, &a01);
//	result_my = ft_printf("my: %%*p = |%*p|\n", 21 &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
	
	
	
	/* Сделать */
//	printf("%-4.9s\n", "0");
//	ft_printf("%-4.9s\n", "0");

	return (0);
}
