#include "libftprintf.h" /* Моя библиотека */
#include <limits.h> /* Для INT_MIN */

int		main(void)
{
	/* Тестирование */
//	printf("Hello it's me %s, year %d and my first letter %c %%\n", "OLEG", 38, 'o');
//	ft_printf("Hello it's me %s, year %d and my first letter %c %%\n", "OLEG", 38, 'o');
//	ft_printf("%d\n%s\n%c\n%%\n%s\n%d\n", 21, "lol", 't', "kek", 17);

	int res_pf;
	int res_my;
	res_my = ft_printf("my: |%.*x|\n", -1, 0);
	res_pf = printf("pf: |%.*x|\n", -1, 0);
	printf("len my: %d\n", res_my);
	printf("len pf: %d\n", res_pf);
//
//	res_my = ft_printf("|%-32s|\n", NULL);
//	res_pf = printf("|%-32s|\n", NULL);
//	printf("len my: %d\n", res_my);
//	printf("len pf: %d\n", res_pf);
	
//	 Ломает ft_check
//	res_my = ft_printf("my: |%42d|\n", 4242);
//	res_pf = printf("pf: |%42d|\n", 4242);
//	printf("len my: %d\n", res_my);
//	printf("len pf: %d\n", res_pf);
	
//	int result1;
//	int result2;
//	char *format;
//	puts("\n\n--------------------------------s--------------------------------");
//	format = "|%0*.*s| |%-4.19s| |%04.13s|";
//	result1 = ft_printf(format, 17, 12, "это русский текст1", "this is a text2", "text2");
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf(format, 17, 12, "это русский текст1", "this is a text2", "text2");
//	printf("\t\tlb result: %d\n\n", result2);
//
//	format = "|%03.6s| |%.1s|";
//	printf("\tmy result: %d\n\n", ft_printf(format, NULL));
//	printf("\tlb result: %d\n\n", printf(format, NULL));
//
//	format = "|%.*s|";
//	printf("\tmy result: %d\n\n", ft_printf(format, -13, "hello"));
//	printf("\tlb result: %d\n\n", printf(format, -13, "hello"));
	
//	puts("\n\n--------------------------------p--------------------------------");
//	long long n1 = 12;
//
//	result1 = ft_printf("|%2p| |%4p| |%4.p| |%1.p|", NULL, NULL, NULL, NULL);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%2p| |%4p| |%4.p| |%1.p|", NULL, NULL, NULL, NULL);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%2p|", &n1);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%2p|", &n1);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%24p| |%24p| |%16p|", &n1, &n1, &n1);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%24p| |%24p| |%16p|", &n1, &n1, &n1);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%24p| |%24p|", &n1, &n1);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%24p| |%24p|", &n1, &n1);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%22.8p| |%4p|", &n1, NULL);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%22.p| |%4p|", &n1, NULL);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%-24p| |%-24p| |%-16p|", &n1, &n1, &n1);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%-24p| |%-24p| |%-16p|", &n1, &n1, &n1);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%-24p| |%-24p| |%-12p|", &n1, &n1, NULL);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%-24p| |%-24p| |%-12p|", &n1, &n1, NULL);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%-25p| |%-24p|", &n1, NULL);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%-25p| |%-24p|", &n1, NULL);
//	printf("\t\tlb result: %d\n\n", result2);
//
//	result1 = ft_printf("|%-17p| |%-6p|", &n1, NULL);
//	printf("\t\tmy result: %d\n", result1);
//	result2 = printf("|%-17p| |%-6p|", &n1, NULL);
//	printf("\t\tlb result: %d\n\n", result2);


	/* МОИ ТЕСТЫ */
//	ft_printf("-------------------------------------\n");
//	ft_printf("---------------d and i---------------\n");
//	ft_printf("-------------------------------------\n");
//	int result_pf;
//	int result_my;
//	result_pf = printf("pf: %%d_neg = |%d|\n", -42);
//	result_my = ft_printf("my: %%d_neg = |%d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-d = |%-d|\n", 42);
//	result_my = ft_printf("my: %%-d = |%-d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0d = |%0d|\n", 42);
//	result_my = ft_printf("my: %%0d = |%0d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-d_neg = |%-d|\n", -42);
//	result_my = ft_printf("my: %%-d_neg = |%-d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0d_neg = |%0d|\n", -42);
//	result_my = ft_printf("my: %%0d_neg = |%0d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3d = |%3d|\n", 42);
//	result_my = ft_printf("my: %%3d = |%3d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3d = |%-3d|\n", 42);
//	result_my = ft_printf("my: %%-3d = |%-3d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03d = |%03d|\n", 42);
//	result_my = ft_printf("my: %%03d = |%03d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3d_neg = |%3d|\n", -42);
//	result_my = ft_printf("my: %%3d_neg = |%3d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3d_neg = |%-3d|\n", -42);
//	result_my = ft_printf("my: %%-3d_neg = |%-3d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03d_neg = |%03d|\n", -42);
//	result_my = ft_printf("my: %%03d_neg = |%03d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13d = |%13d|\n", 424242);
//	result_my = ft_printf("my: %%13d = |%13d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13d_neg = |%13d|\n", -424242);
//	result_my = ft_printf("my: %%13d_neg = |%13d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6d = |%6d|\n", 424242);
//	result_my = ft_printf("my: %%6d = |%6d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6d_neg = |%6d|\n", -424242);
//	result_my = ft_printf("my: %%6d_neg = |%6d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13d = |%-13d|\n", 424242);
//	result_my = ft_printf("my: %%-13d = |%-13d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13d_neg = |%-13d|\n", -424242);
//	result_my = ft_printf("my: %%-13d_neg = |%-13d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013d = |%013d|\n", 424242);
//	result_my = ft_printf("my: %%013d = |%013d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013d_neg = |%013d|\n", -424242);
//	result_my = ft_printf("my: %%013d_neg = |%013d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	result_pf = printf("pf: %%.d = |%.d|\n", 42);
//	result_my = ft_printf("my: %%.d = |%.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%.d_neg = |%.d|\n", -42);
//	result_my = ft_printf("my: %%.d_neg = |%.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-.d = |%-.d|\n", 42);
//	result_my = ft_printf("my: %%-.d = |%-.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0.d = |%0.d|\n", 42);
//	result_my = ft_printf("my: %%0.d = |%0.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-.d_neg = |%-.d|\n", -42);
//	result_my = ft_printf("my: %%-.d_neg = |%-.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%0.d_neg = |%0.d|\n", -42);
//	result_my = ft_printf("my: %%0.d_neg = |%0.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3.d = |%3.d|\n", 42);
//	result_my = ft_printf("my: %%3.d = |%3.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3.d = |%-3.d|\n", 42);
//	result_my = ft_printf("my: %%-3.d = |%-3.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03.d = |%03.d|\n", 42);
//	result_my = ft_printf("my: %%03.d = |%03.d|\n", 42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%3.d_neg = |%3.d|\n", -42);
//	result_my = ft_printf("my: %%3.d_neg = |%3.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-3.d_neg = |%-3.d|\n", -42);
//	result_my = ft_printf("my: %%-3.d_neg = |%-3.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%03.d_neg = |%03.d|\n", -42);
//	result_my = ft_printf("my: %%03.d_neg = |%03.d|\n", -42);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13.d = |%13.d|\n", 424242);
//	result_my = ft_printf("my: %%13.d = |%13.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%13.d_neg = |%13.d|\n", -424242);
//	result_my = ft_printf("my: %%13.d_neg = |%13.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6.d = |%6.d|\n", 424242);
//	result_my = ft_printf("my: %%6.d = |%6.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%6.d_neg = |%6.d|\n", -424242);
//	result_my = ft_printf("my: %%6.d_neg = |%6.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13.d = |%-13.d|\n", 424242);
//	result_my = ft_printf("my: %%-13.d = |%-13.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-13.d_neg = |%-13.d|\n", -424242);
//	result_my = ft_printf("my: %%-13.d_neg = |%-13.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013.d = |%013.d|\n", 424242);
//	result_my = ft_printf("my: %%013.d = |%013.d|\n", 424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%013.d_neg = |%013.d|\n", -424242);
//	result_my = ft_printf("my: %%013.d_neg = |%013.d|\n", -424242);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len my: %d\n", result_my);
	
	
//	ft_printf("-------------------------------------\n");
//	ft_printf("------------------p------------------\n");
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%p = |%p|\n", &a01);
//	result_my = ft_printf("my: %%p = |%p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-p = |%-p|\n", &a01);
//	result_my = ft_printf("my: %%-p = |%-p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%1p = |%1p|\n", &a01);
//	result_my = ft_printf("my: %%1p = |%1p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%4p = |%4p|\n", &a01);
//	result_my = ft_printf("my: %%4p = |%4p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-4p = |%-4p|\n", &a01);
//	result_my = ft_printf("my: %%-4p = |%-4p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%20p = |%20p|\n", &a01);
//	result_my = ft_printf("my: %%20p = |%20p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-20p = |%-20p|\n", &a01);
//	result_my = ft_printf("my: %%-20p = |%-20p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%-20p = |%-20p|\n", &a01);
//	result_my = ft_printf("my: %%-20p = |%-20p|\n", &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
//	ft_printf("-------------------------------------\n");
//	result_pf = printf("pf: %%*p = |%*p|\n", 21, &a01);
//	result_my = ft_printf("my: %%*p = |%*p|\n", 21 &a01);
//	ft_printf("len pf: %d\n", result_pf);
//	ft_printf("len pf: %d\n", result_my);
	return (0);
}
